### ISSUE TITLE
Support ForceAuthn=true

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxShibboleth#10]
Section 4.1.3.4 of the SAML-Profile document (in the Web SSO Profile section), it specifies:

```
The ForceAuthn <AuthnRequest>attribute, if present with a value of true, obligates the identity provider to freshly establish this identity, rather than relying on an existing session it may have with the principal.
```

It would be nice if we could support this. 

In OpenID Connect we can use the `prompt=login` parameter to do something similar.

**Comment by dmogn** [comment]
We need rewrite Shib. IDP RemoteUser flow for ForceAuthn support.

Default "RemoteUser" does not support it.

**Comment by yurem** [comment]
Done

**Comment by yurem** [comment]
For documentation.

Our oxAuth IDP3 plugin do translation Saml ForceAuthn=true to OpenID AuthZ request Prompt.Login
There is more info about each part in Saml and OpenID specs
