### ISSUE TITLE
Issues with MySQL

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/oxShibboleth#116]
When idp is installed with MySQL backend, we have many errors in log files. Please see log files.
[idp-logs.zip](https://github.com/GluuFederation/oxShibboleth/files/7814245/idp-logs.zip)

**Comment by uprightech** [comment]
Hello @mbaser  

@yurem submitted a [commit](https://github.com/GluuFederation/community-edition-setup/commit/36b554c310333e1e16a79f89325857e783b3785d) containing data to append to `global.xml` as is done in the case for couchbase (check out the `saml_couchbase_settings()` method in the `setup_app/installers/saml.py` file in the installer.

**Comment by mbaser** [comment]
Issues with MySQL was resolved with latest package and setup.py
