### ISSUE TITLE
RequestedAuthnContext throws weird page

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxShibboleth#13]
I was testing a SAML client that included this in the `AuthnRequest`

```
<samlp:AuthnRequest
   <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>
            urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
        </saml:AuthnContextClassRef>
   </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```
I was surprised when I got back this form... which is certainly not going to work:

![image](https://cloud.githubusercontent.com/assets/3717101/17978000/9514c8b8-6ab9-11e6-9f1a-1db5def46f24.png)

As a starting position, maybe we should just update this page with html that redirects to oxAuth? 

Or return an error page that says `RequestedAuthnContext` not supported.

**Comment by mzico** [comment]
@nynymike : let's try to comment out U/P login handler and restart tomcat.  Configuration file: handler.xml, location: /opt/idp/conf

Here is what I meant...

```
    <!--  Username/password login handler -->

<!--
    <ph:LoginHandler xsi:type="ph:UsernamePassword"
                  jaasConfigurationLocation="file:///opt/idp/conf/login.config">
        <ph:AuthenticationMethod>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</ph:AuthenticationMethod>
    </ph:LoginHandler>
-->
```

**Comment by nynymike** [comment]
[Moved to community-edition-setup](https://github.com/GluuFederation/community-edition-setup/issues/168)
