### ISSUE TITLE
SLO page is not included in IDP metadata

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxShibboleth#14]
There is no SLO binding or URL in the standard Gluu Server IDP metadata.

**Comment by OneLoveAmaru** [comment]
So now that SLO is included, it breaks the metadata. When I try to upload the metadata to testshib, it says: "The file you are attempting to upload is not valid metadata. Please correct any errors and try again."

I had to remove the 3 lines for SLO for it to work.

If you take the metadata and try to verify it at: https://www.samltool.com/validate_xml.php it also hits on the SLO lines.

I don't know enough on how to fix this but something is obviously wrong.

**Comment by OneLoveAmaru** [comment]
You can take a look at our IDP Metadata here: https://sso.threattrack.net/idp/shibboleth

**Comment by nynymike** [comment]
Duplicate: https://github.com/GluuFederation/oxShibboleth/issues/24
