### ISSUE TITLE
Map AuthnContextClassRef --> acr in OpenID Connect

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxShibboleth#15]
In SAML, an AuthnRequest may contain an `AuthnContextClassRef` like this

```
<samlp:AuthnRequest
   <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>
            urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
        </saml:AuthnContextClassRef>
   </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

It would be amazing if we could somehow sent this as the acr param in the openid connect authn request.

Also see this [blog](http://blog.samlsecurity.com/2011/01/redirect-with-authnrequest.html)

**Comment by willow9886** [comment]
@aliaksander-samuseu can you assess this and determine the best develop to assign?

**Comment by malotian** [comment]
work in progress - support to receive/parse AuthContextClassRef from http request

**Comment by malotian** [comment]
Implemented and tested successfully
