### ISSUE TITLE
Upgrade to Shibboleth v3.3.0

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxShibboleth#18]
https://wiki.shibboleth.net/confluence/display/NEWS/2016/11/10/Shibboleth+Identity+Provider+V3.3.0+Released

**Comment by dmogn** [comment]
Our config templates are based on v3.2.1

**Comment by dmogn** [comment]
Heh :) Solved in v3.3.0:

Collision in LDAP Data Connector result set cache
=================================================
A flaw in the implementation of the result cache in the LDAP data
connector [1] in the attribute resolver can cause results for one search
to be substituted for another search, including one associated with a
different subject. Depending on the purpose of the search and the
attributes involved, this can result in data associated with one user
being substituted for another, with critical impact on connected
systems, up to and including improper information disclosure.

It is believed at this time that this flaw is present in the V3
software only, and does not affect the older V2 Identity Provider
software.

**Comment by dmogn** [comment]
Done. v. 3.3.1

**Comment by yurem** [comment]
I reverted it and re-open issue due to issue:
```
[/opt/shibboleth-idp/system/flows/cas/login/../cas-abstract-beans.xml]; nested exception is java.lang.ClassNotFoundException: net.shibboleth.idp.cas.flow.impl.ValidateIdpSessionAction
```

**Comment by dmogn** [comment]
Fixed.

**Comment by dmogn** [comment]
setup.py exeption with RC1:

22:53:08 08/11/17 Running: /opt/jre/bin/java -classpath /opt/dist/gluu/idp3_cml_keygenerator.jar org.xdi.oxshibboleth.keygenerator.KeyGenerator /opt/shibboleth-idp/credentials hNN1IgdRl3GB

22:53:10 08/11/17 java.io.IOException: Keystore was tampered with, or password was incorrect
        at com.sun.crypto.provider.JceKeyStore.engineLoad(JceKeyStore.java:865)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.xdi.oxshibboleth.keygenerator.Keystore.<init>(Keystore.java:46)
        at org.xdi.oxshibboleth.keygenerator.KeyGenerator.main(KeyGenerator.java:32)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
        ... 4 more
java.security.KeyStoreException: Uninitialized keystore
        at java.security.KeyStore.containsAlias(KeyStore.java:1252)
        at org.xdi.oxshibboleth.keygenerator.Keystore.addKey(Keystore.java:89)
        at org.xdi.oxshibboleth.keygenerator.KeyGenerator.main(KeyGenerator.java:33)

**Comment by dmogn** [comment]
Fixed.
