### ISSUE TITLE
CE 3.0.0 Shibboleth: Unable to create Trust Relationship [ File method ]

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxShibboleth#19]
Situation: Trying to create a trust relationship with SP metadata but it's failing. 

Background check: 

- Seems like oxTrust is generating ldap entry for new trust relationship
- But oxTrust is unable to transfer metadata from `/opt/shibboleth-idp/temp_metadata` location to `/opt/shibboleth-idp/metadata` after validation checking. 
- Which is resulting System Error with stack trace "Unable to read metadata" ( Because it's not present in /metadata location ). 

Stack trace: 

- As you can see, when I went to create a new TR; it's metadata is inside `temp_metadata`: 
```
jetty@proxy:/opt/shibboleth-idp/temp_metadata$ ls
79A0789975C4F4890002C85F45860006BE899BFD-sp-metadata.xml1D0D.B83C  79A0789975C4F4890002C85F45860006FF0E277D-sp-metadata.xml109F.AAA6
jetty@proxy:/opt/shibboleth-idp/temp_metadata$
```
- However it's not transferring to stable 'metadata' location ( The workflow is: after validating metadata; it should be transferred to 'metadata' location ) 

```
jetty@proxy:/opt/shibboleth-idp/metadata$ ls
79A0789975C4F4890002C85F4586000620B378B3-sp-metadata.xml  idp-metadata.xml
jetty@proxy:/opt/shibboleth-idp/metadata$ pwd
/opt/shibboleth-idp/metadata
jetty@proxy:/opt/shibboleth-idp/metadata$
```
- From oxtrust.log: http://pastebin.com/PeDYttGc

**Comment by mzico** [comment]
@dmogn @uboznikov

**Comment by mzico** [comment]
Seems like there is [another](https://github.com/GluuFederation/oxTrust/issues/416) ticket on same issue. Closing this one.

**Comment by uboznikov** [comment]
@mzico For reference before beta I tested it ok:

[gluu-server 3.0 oxTrust ui SAML2SSO configuration missing](https://github.com/GluuFederation/oxTrust/issues/405#issuecomment-266673288)
