### ISSUE TITLE
Load configuration from LDAP

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxShibboleth#2]
Mike Schwartz: Upgrade Shib 3 to store config in LDAP 
Mike Schwartz: There are three files we normally modify...
Mike Schwartz: relying-party.xml, attribute-filter.xml and attribute-release.xml

**Comment by dmogn** [comment]
https://github.com/GluuFederation/oxTrust/issues/307#issuecomment-264371276

**Comment by nynymike** [comment]
There is a new feature to load config from http.. I think this would be a better approach
