### ISSUE TITLE
Don't show stacktrace... ever

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxShibboleth#25]
A customer was showing me a 500 error from shibboleth that printed a full Java stacktrace, which should only be present in the logs. We never want to publish a stacktrace to users.

**Comment by yurem** [comment]
@nynymike Do you remember IDP version and how to reproduce it?

During last 2 years we updated IDP few times. Probably this issue is out of date now

**Comment by yurem** [comment]
I can't reproduce it in recent versions.
