### ISSUE TITLE
SAML metadata is not processing properly

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxShibboleth#30]
Two situations in 3.1.0 RC2: 

 - After uploading metadata, IDP is storing that as `E3CCCC59179506D50002EC5321BD00064AB92AD4-sp-metadata.xml31A7.3F8C` [ Note that '31A7.3F8C' part after .abc-sp-metadata.xml ]. Correct one should be: `E3CCCC59179506D50002EC5321BD00064AB92AD4-sp-metadata.xml`

 - IDP is not cleaning that metadata even after I delete the trust relationship from oxTrust. Screenshot attached. 

![screenshot_1](https://user-images.githubusercontent.com/7156097/29323483-a62f7a58-81a6-11e7-93ca-e86e275f6108.png)

**Comment by yurem** [comment]
@mzico I'm closing it. Please reopen i it still actual issue.
