### ISSUE TITLE
conversation state not found for a key

### ISSUE THREAD

**Issue by rajnikantsh** [GluuFederation/oxShibboleth#34]
I can see following log trace in idp-process.log

ERROR [net.shibboleth.idp.authn.ExternalAuthenticationException:76] - net.shibboleth.idp.authn.ExternalAuthenticationException: No conversation state found in session for key (e1s1)	at net.shibboleth.idp.authn.ExternalAuthentication.startExternalAuthentication(ExternalAuthentication.java:142)

while redirecting user on redirct uri in passport authentication

**Comment by dmogn** [comment]
I've checked  gluu-server-3.1.1_1.7~trusty+Ub14.04_amd64.deb. Shib IDP works well out of the box. 
Both flows SP->Shib IDP;   SP->Asimba->Shib IDP->Asimba->SP works.

We need find defference with passport flow.

**Comment by dmogn** [comment]
Flow:  RP->oxAuth1->Shib IDP -> oxAuth1 ->Shib IDP->oxAsuth1->RP 
Browser: google chrome in incognito mode

**Comment by nynymike** [comment]
This is very unlikely a problem with shibboleth.
