### ISSUE TITLE
Create authentication flow to replace RemoteUser flow

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxShibboleth#35]
Now our oxShibboleth authentication based on servlet filters and empty RemoteUser flow.
This solution has limited capabilities:
- No ForceAuthn support in RemoteUser flow.
- No server-side session support (so logout distribution is impossible).

**Comment by aliaksander-samuseu** [comment]
Having support for "ForceAuthn" flag surely would help, in IDPv3 used in 3.x packages it now results in failed login flow OOTB if some app uses this flag.

**Comment by yurem** [comment]
We need to replace our integration approach. We are using in IDP3 our IDP2 solution. IDP3 supports extension. There are few of them: https://wiki.shibboleth.net/confluence/display/IDP30/Contributions+and+Extensions#ContributionsandExtensions-IdentityProviderExtensions We can use one of them as example.

**Comment by yurem** [comment]
Starting from 3.1.4 we use own IDP3 Authn flow `Authn/oxAuth`

**Comment by yurem** [comment]
Implement. We added oxAuth flow
