### ISSUE TITLE
Check the IdP-initiated flow capability

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxShibboleth#4]
Ryan Kinzy: ... they want to do an IDP initiated workflow for a customer.
...

SAML standard:
"SAML V2.0 supports both the IdP-initiated and SP-initiated flows."
http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html

**Comment by nynymike** [comment]
I don't see how IDP initiated workflow effects the Gluu Server... its an SP issue.
