### ISSUE TITLE
Override Logout Functionality

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxShibboleth#5]
SAML initiated logout doesn't work. We can probably redirect to OpenID Connect front channel logout, although SP's won't be notified about the logout event. Perhaps we can add SP's as sessions under the client (with respective logout URLs) so the iframes are rendered properly in the front channel logout page.

Another issue is that in a cluster, other shib IDP servers may have active sessions in memory. This solution may also require memcached session storage to really work in a cluster.

**Comment by yurem** [comment]
We support both IDP/SP initiated logout in recent builds
