### ISSUE TITLE
Couchbase Support

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxShibboleth#59]
The Shibboleth IDP gets attributes from LDAP (ldap.conf).  In Gluu Server 4.0, we are allowing Couchbase as a database backend. If this is the case, Shib will need to get attributes from Couchbase instead.  

Note: one theory is that this is not necessary because couchbase has a sql interface, and perhaps that could be used.

**Comment by yurem** [comment]
It's implemented already. You can install current beta build with either Couchbase or Hybrid persistence layer. In Couchbase mode we uses free JDBC driver. We made it [fork](https://github.com/GluuFederation/gluu-jdbc-cb) and fixed few bugs in it. In 4.1 we added one small update to this fork described in this [issue](https://github.com/GluuFederation/oxTrust/issues/1666).

**Comment by yurem** [comment]
We need to do QA of it to get feadback

**Comment by malotian** [comment]
@sahiliamsso to update on QA

**Comment by yurem** [comment]
Done
