### ISSUE TITLE
IDP throws exception after CE install

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxShibboleth#65]
Here is stack trace:

```
Offending resource: URL [file:/opt/shibboleth-idp/conf/authn/general-authn.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file:/opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml]; nested exception is java.io.FileNotFoundException: /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml (No such file or directory)
    at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:70)
    at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:118)
    at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:103)
    at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:259)
    at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseDefaultElement(DefaultBeanDefinitionDocumentReader.java:184)
    at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:169)
```

**Comment by malotian** [comment]
osboxes@osboxes:~/Downloads$ wget https://repo.gluu.org/ubuntu/pool/main/bionic-devel/gluu-server_4.0-rc1-88~bionic+Ub18.04_amd64.deb
--2019-09-16 12:56:32--  https://repo.gluu.org/ubuntu/pool/main/bionic-devel/gluu-server_4.0-rc1-88~bionic+Ub18.04_amd64.deb
Resolving repo.gluu.org (repo.gluu.org)... 165.227.82.89
Connecting to repo.gluu.org (repo.gluu.org)|165.227.82.89|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 794237040 (757M) [application/x-debian-package]
Saving to: ‘gluu-server_4.0-rc1-88~bionic+Ub18.04_amd64.deb’

gluu-server_4.0-rc1-88~bionic+Ub18.04_amd64.deb          100%[================================================================================================================================>] 757.44M  13.0MB/s    in 42s

2019-09-16 12:57:14 (17.9 MB/s) - ‘gluu-server_4.0-rc1-88~bionic+Ub18.04_amd64.deb’ saved [794237040/794237040]

(failed reverse-i-search)`dpl': cat /opt/gluu-server-3.1.6/opt/gluu/jetty/identity/conf/shibboleth3/i^C/saml-nameid.xml.vm
(failed reverse-i-search)`': wget https://repo.gluu.org/ubuntu/pool/main/bionic-devel/gluu-^Crver_4.0-rc1-88~bionic+Ub18.04_amd64.deb
osboxes@osboxes:~/Downloads$ ^C
osboxes@osboxes:~/Downloads$ sudo dpkg -i gluu-server_4.0-rc1-88~bionic+Ub18.04_amd64.deb
[sudo] password for osboxes:
Selecting previously unselected package gluu-server.
(Reading database ... 172532 files and directories currently installed.)
Preparing to unpack gluu-server_4.0-rc1-88~bionic+Ub18.04_amd64.deb ...
Unpacking gluu-server (4.0-rc1-88~bionic+Ub18.04) ...
Setting up gluu-server (4.0-rc1-88~bionic+Ub18.04) ...
Created symlink /etc/systemd/system/machines.target.wants/systemd-nspawn@gluu_server.service → /lib/systemd/system/systemd-nspawn@gluu_server.service.
Starting gluu-server ...
Extracting community-edition-setup package
osboxes@osboxes:~/Downloads$ sudo /sbin/gluu-serverd enable
osboxes@osboxes:~/Downloads$ sudo /sbin/gluu-serverd start
osboxes@osboxes:~/Downloads$ sudo /sbin/gluu-serverd login
Welcome to the Gluu Server!
Last login: Mon Sep 16 12:59:47 2019 from 127.0.0.1
root@localhost:~# cd /install/community-edition-setup/
root@localhost:/install/community-edition-setup# ./setup.py

Installing Gluu Server...
Detected OS  :  ubuntu
Detected init:  systemd
Detected Apache:  2.4

Installing Gluu Server...

For more info see:
  /install/community-edition-setup/setup.log
  /install/community-edition-setup/setup_error.log


** All clear text passwords contained in /install/community-edition-setup/setup.properties.last.

Do you acknowledge that use of the Gluu Server is under the MIT license? [N|y] : y
Enter IP Address [192.168.0.31] :
Enter hostname [osboxes] : test.gluu.org
Enter your city or locality : Brampton
Enter your state or province two letter code : OM
Enter two letter Country Code : CA
Enter Organization Name : GLOO
Enter email address for support at your organization : malotian@gluu.org
Enter maximum RAM for applications in MB [3072] :
Optional: enter password for oxTrust and DB superuser [Y75zOe%VB!My] : Infosys@123
Install oxAuth OAuth2 Authorization Server? [Yes] :
Install oxTrust Admin UI? [Yes] :
Install Backend DB Server? [Yes] :
Install Apache HTTPD Server [Yes] :
Install Shibboleth SAML IDP? [No] : Yes
Install oxAuth RP? [No] :
Install Passport? [No] :
Install Gluu Radius? [No] :

hostname                                            test.gluu.org
orgName                                                      GLOO
os                                                         ubuntu
city                                                     Brampton
state                                                          OM
countryCode                                                    CA
Applications max ram                                         3072
Install oxAuth                                               True
Install oxTrust                                              True
Install Backend                                              True
Backend Type                                                 Ldap
Java Type                                                     jre
Install Apache 2 web server                                  True
Install Shibboleth SAML IDP                                  True
Install oxAuth RP                                           False
Install Passport                                            False
Install Gluu Radius                                         False


Proceed with these values [Y|n] Y
Installing [#################################] Completed


 Gluu Server installation successful! Point your browser to https://test.gluu.org


root@localhost:/install/community-edition-setup# ls -lart /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml
-rw-r--r-- 1 jetty jetty 1718 Sep 16 14:59 /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml
root@localhost:/install/community-edition-setup# cat /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:util="http://www.springframework.org/schema/util"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:c="http://www.springframework.org/schema/c"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
                           http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
                           http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd"
       default-init-method="initialize"
       default-destroy-method="destroy">

           <bean id="authn/oxAuth" parent="shibboleth.AuthenticationFlow"
                p:forcedAuthenticationSupported="true"
                p:nonBrowserSupported="false" >
            <property name="supportedPrincipals">
                <list>
                    <bean parent="shibboleth.SAML2AuthnContextClassRef"
                        c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol" />
                    <bean parent="shibboleth.SAML2AuthnContextClassRef"
                        c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:Password" />
                    <bean parent="shibboleth.SAML2AuthnContextClassRef"
                        c:classRef="urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport" />
                </list>
            </property>
           </bean>
</beans>root@localhost:/install/community-edition-setup#

**Comment by malotian** [comment]
Interesting!!!

**Comment by malotian** [comment]
even logs are observed 

```
root@localhost:/opt/gluu/jetty/idp/logs# fgrep -R "BeanDefinitionStoreException" *
2019_09_16.jetty.log:Offending resource: URL [file:/opt/shibboleth-idp/conf/authn/general-authn.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file:/opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml]; nested exception is java.io.FileNotFoundException: /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml (No such file or directory)
2019_09_16.jetty.log:Offending resource: URL [file:/opt/shibboleth-idp/conf/authn/general-authn.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file:/opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml]; nested exception is java.io.FileNotFoundException: /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml (No such file or directory)
2019_09_16.jetty.log:Offending resource: URL [file:/opt/shibboleth-idp/conf/authn/general-authn.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file:/opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml]; nested exception is java.io.FileNotFoundException: /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml (No such file or directory)
2019_09_16.jetty.log:Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file:/opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml]; nested exception is java.io.FileNotFoundException: /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml (No such file or directory)
2019_09_16.jetty.log:org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from relative location [general-authn-system.xml]|Offending resource: URL [file:/opt/shibboleth-idp/system/conf/global-system.xml]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from relative location [../../conf/authn/general-authn.xml]|Offending resource: URL [file:/opt/shibboleth-idp/system/conf/general-authn-system.xml]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from relative location [oxauth-supported-principals.xml]|Offending resource: URL [file:/opt/shibboleth-idp/conf/authn/general-authn.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file:/opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml]; nested exception is java.io.FileNotFoundException: /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml (No such file or directory)
2019_09_16.jetty.log:org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from relative location [../../conf/authn/general-authn.xml]|Offending resource: URL [file:/opt/shibboleth-idp/system/conf/general-authn-system.xml]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from relative location [oxauth-supported-principals.xml]|Offending resource: URL [file:/opt/shibboleth-idp/conf/authn/general-authn.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file:/opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml]; nested exception is java.io.FileNotFoundException: /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml (No such file or directory)
2019_09_16.jetty.log:org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from relative location [oxauth-supported-principals.xml]|Offending resource: URL [file:/opt/shibboleth-idp/conf/authn/general-authn.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file:/opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml]; nested exception is java.io.FileNotFoundException: /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml (No such file or directory)
2019_09_16.jetty.log:org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file:/opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml]; nested exception is java.io.FileNotFoundException: /opt/shibboleth-idp/conf/authn/oxauth-supported-principals.xml (No such file or directory)
```

**Comment by malotian** [comment]
fixed via https://github.com/GluuFederation/oxShibboleth/commit/325af029f4ed95a6a87f0eaac5fc03e74f385a82
