### ISSUE TITLE
Support Couchbase for cache IDP sessions

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxShibboleth#67]
In IDP3 there are few supported [cache ](https://wiki.shibboleth.net/confluence/display/IDP30/StorageConfiguration#StorageConfiguration-MemcachedStorageService) mechanisms.

According to documentation to activate Memcached cache to store sessions we need to do:

1.
```
Add to /opt/shibboleth-idp/system/conf/global-system.xml (or /etc/global-system.xml):

     <bean id="shibboleth.MemcachedStorageService"
          class="org.opensaml.storage.impl.memcached.MemcachedStorageService"
          c:timeout="2">
        <constructor-arg name="client">
            <bean class="net.spy.memcached.spring.MemcachedClientFactoryBean"
                  p:servers="localhost:11211"
                  p:protocol="BINARY"
                  p:locatorType="CONSISTENT"
                  p:failureMode="Redistribute">
                <property name="hashAlg">
                    <util:constant static-field="net.spy.memcached.DefaultHashAlgorithm.FNV1_64_HASH" />
                </property>
                <property name="transcoder">
                    <!-- DO NOT MODIFY THIS PROPERTY -->
                    <bean class="org.opensaml.storage.impl.memcached.StorageRecordTranscoder" />
                </property>
            </bean>
        </constructor-arg>
    </bean>
```
2. Update `/conf/idp.properties` to specify:
idp.session.StorageService = shibboleth.MemcachedStorageService

We can use this cache implementation as reference to prepare CouchbaseStorageService for IDP. It should use java SDK to rich maximum performance.

Also there is [Redis](https://github.com/UniconLabs/shibboleth-redis-storage-service) implementation. We can use either RedisStorageService or MemcachedStorageService

**Comment by mbaser** [comment]
In my opinion redis sentinel support will be better.

**Comment by yurem** [comment]
Implemented

**Comment by yurem** [comment]
Now we uses GluuStorageService
