### ISSUE TITLE
refactor uber.patch to logical units

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxShibboleth#73]
[Yure Comments]
Also it’s not very good for support

We used split patches before:

https://github.com/GluuFederation/oxShibboleth/tree/master/static/src/main/patches

And it’s clear what every patch do.

It’s easier to maintain a series of patches so we can turn off a patch without breaking the configuration.

**Comment by malotian** [comment]
@yurem I can break it into individual patches, But its difficult to maintain with every upgrade.
here the way I do, I Install current Gluu IDP then I install vanilla IDP (shibb), then doing diff at root level and create a patch.

with individual patches, this process becomes too much cumbersome (and error prone) as we may minor upgrades - headers/comments. because some files are changes in whitespaces.

what I can suggest is that after uber patch, we can create separate patch for each file. and a README file telling what patch corresponds to what sort of changes. that will be maintainable approach.

I have gone through the process of IDP4 Upgrade, and I know its not easy to maintain logical patches. as there were lof changes in tags, structures... one or another was being missed and was getting failures.

**Comment by uprightech** [comment]
Implemented
