### ISSUE TITLE
Issue on SAML assertion generation  attributes like mail,sn,givenname etc  is released twice .

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxShibboleth#76]
## Describe the issue
Issue on SAML assertion generation  attributes like mail,sn,givenname etc  is released twice .
## Steps To Reproduce
1. loging to gluu-server. 
2. go to SAML 
3. Create new Trust Relationship using desire samltestprovider(my case sptest.iamshowcase)
4.  Test saml and check SAML Assertion .

## Expected behavior
Assestion must have each attribute value only one time.
## Actual behavior
Each attribute value is displayed twice.

## Screenshots
![samlissue](https://user-images.githubusercontent.com/34593983/86903081-78f0f300-c12c-11ea-917e-5c288d295fc8.png)

## Desktop (please complete the following information):
 - OS: Ubuntu 18
 - Gluu version 4.2

**Comment by malotian** [comment]
fixed https://github.com/GluuFederation/oxTrust/commit/6ace4554e707423968ea3bcf4093db3ce9b6c101
https://github.com/GluuFederation/oxShibboleth/commit/8dea59665ad797c279aea0b589b00f6a5a0fbd0e
