### ISSUE TITLE
Shibb customization not working

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxShibboleth#88]
Customization for Shibb error page or any Shibb related pages should reflect from directory structure: 

```
[root@xxx custom]# pwd
/opt/gluu/jetty/idp/custom
[root@xxx custom]# ls
logo  pages  static
[root@xxx custom]# cd logo/
[root@xxx logo]# ls
logo.png
[root@xxx logo]# 
```

But it's not reflecting properly. As for example, I am trying to change logo of below page but this is not happening...

![Screenshot at 2021-08-12 09-55-20](https://user-images.githubusercontent.com/7156097/129219349-8ceca10e-332c-4298-aecf-b0507fe73643.png)

**Comment by aveekbu** [comment]
IMHO, changing the logo location to "/opt/gluu/jetty/idp/servlet/logo" should fix the issue.

**Comment by mookkiah** [comment]
When fixing this issue, it is good idea to customize the entire page not jus the logo.
