### ISSUE TITLE
Code migration to Shibboleth IDP 4.1.4

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxShibboleth#93]
As of the creation of this issue , the current Shibboleth IDP version being used is 4.0.1 , which is also EOL.
The current stable version of Shibboleth IDP is 4.1.4 .
In Shibboleth IDP 4.1.4 , major architectural changes were made, which affected how code is now added to 
Shibboleth IDP. Plugins/ modules were introduced , making for a cleaner installation process. 
The objectives in this issue are:
  - Do a list of potential modules for our plugin 
  - create/move code into our plugins , including configuration data and code from the `shib-oxauth-authn3` project

**Comment by mzico** [comment]
@uprightech : great initiative!
