### ISSUE TITLE
Ensure separation of handling of different SAML ACRs when IDP decides whether or not to use SSO for a particular request

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxShibboleth#94]
Currently, if an authenticated session is created at IDP after serving a SAML request containing a particular ACR (or no ACR at all), it will be re-used to serve any subsequent requests even when they reference different (and more secure) ACRs (SSO). Specifically, if a more secure ACR is requested (like, for MFA auth), no re-authentication will happen, yet in SAML response the requested ACR will still be listed as if it was actually used (as noted by a customer in ticket 9937)

This may happen because of the way our custom auth plugin handles certain internal IDP objects. Ideally, we would need to separate handling of different SAML ACRs, and in case a new one is requested, redirect user to oxAuth with a proper corresponding `&acr_values=` parameter in request, and let it decide if user needs to authenticate themselves again.

Though to some extent this can be mitigated by SP that requires another (more secure) method to always add "forceAuthn=true" flag to its requests, this is less flexible approach and in many cases may result in forcing user to un-needlessly re-authenticate themselves (while they've already had a session created with the requested auth method anyway).

**Comment by nynymike** [comment]
We'll have to consider whether or not to undertake this, and see what other implementations do. This is not consistent with how we handle the situation in OpenID Connect, where we do require the RP to use `prompt=login`, i.e. the equivalent of `forceAuthn=true`.

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxTrust/commit/0ada0c1166b5e7a458a12b182e51efd3642182cc

**Comment by yurem** [comment]
https://github.com/GluuFederation/shib-oxauth-authn3/commit/dd7f8405f5fdd751944be7faabf88e39e841ba1b
https://github.com/GluuFederation/shib-oxauth-authn3/commit/b2e55a74256ebed3bf19d5b5f972259a3a1b7cb8
https://github.com/GluuFederation/shib-oxauth-authn3/commit/c83b005f1041a768f8b80487997f6ac676fb71c6

**Comment by aliaksander-samuseu** [comment]
@nynymike 

At oxAuth we also have script's Levels feature, which will allow a more secure method with a higher Level - when it's requested via `&acr_values=` parameter - to "beat" session associated with an auth method of a lesser Level,  as if "prompt=login" was used. The customer asked for this behaviour to be consistent across both SAML and OIDC "realms" - as they have both SAML and OIDC SPs/RPs using their Gluu Server deployment, and intend to employ a complex interconnected system of auth flows in that setup.

As of now, they can force user to re-authenticated in OIDC flow by simply specifying a more high-Level ACR (without using "prompt=login") - but they can't do a similar thing for their SAML SP - because if session is already there, SSO will happen regardless of ACR requested.

**Comment by yurem** [comment]
https://github.com/GluuFederation/shib-oxauth-authn3/commit/f7cef400dbd6e3e7acff0fe1251fb9b950466bb9
